### ISSUE TITLE
Attribute 'CombinedReader' not find in converter p2s

### ISSUE THREAD

**Issue by heboquet** [Psy-Fer/project_blue_crab#4]
Hello,

I’m working with slow5 files and I need to convert pod5 to slow5 file. I followed the readme and I try to use _converter.py p2s_ but I have an error with the pod5_format module:

> Traceback (most recent call last):
>   File "/env/export/bigtmp2/hboquet/pod/project_blue_crab/tools/converter.py", line 193, in <module>
>     main()
>   File "/env/export/bigtmp2/hboquet/pod/project_blue_crab/tools/converter.py", line 181, in main
>     pod52slow5(args)
>   File "/env/export/bigtmp2/hboquet/pod/project_blue_crab/tools/converter.py", line 83, in pod52slow5
>     file = pod5_format.CombinedReader(pod5_file)
> AttributeError: module 'pod5_format' has no attribute 'CombinedReader'

I installed (with pip install) and imported all modules (all imports are OK), but I don't find the attribute 'CombinedReader'.
Do you know why I have this error ? 

Thanks,
H

**Comment by Psy-Fer** [comment]
Hello,

Because of how often pod5 is changing/fixing bugs and issues with its library, there is a good chance this repo won't be compatible with pod5 files at the moment. We will maintain converters for pod5 <-> slow5 in the future, but it's just unrealistic to try and keep on top of all the changes to pod5.

So the best and most stable way to go from pod5 to slow5, is by going pod5 to fast5 with the pod5 conversion tools, then from. Fast5 to slow with slow5tools f2s.

I'll look into this problem anyway in a few days (4 day weekend here on Australia) and make a fix, but hopefully this helps in the short term.

Cheers,

James

**Comment by Psy-Fer** [comment]
Looking at the error, looks like an issue with the pod5 library changing its API... Again...

**Comment by heboquet** [comment]
Hello!

Thanks for quick reply. I think I will use slow5tools and pod5 conversion to convert my pod5 to slow5... 
I understand why you maintain converters in the futur, I hope pod5 will be stable soon 👍 

Have a nice week-end,
H
